pool:
  vmImage: ubuntu-latest
trigger: 
 branches:
    include:
      - master
     
steps:
- task: CopyFiles@2
  displayName: Copy json
  inputs:
    Contents: '*.json'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  displayName: Copy ps1
  inputs:
    Contents: '*.ps1'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts